//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtWork()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string awID { get; set; }
        public string awName { get; set; }
        public Nullable<decimal> awPrice { get; set; }
        public string awDescription { get; set; }
        public byte[] awImage { get; set; }
        public Nullable<int> stockQty { get; set; }
        public string categoryID { get; set; }
        public string materialUsed { get; set; }
        public string artistID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
